=== clacoa/epam_edu/Chuggington1/src/main/resources/trains.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="Chuggington">
	<xs:include schemaLocation="train.xsd" />
	<xs:element name="trains">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="train" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string" />
							<xs:element name="throwTunnelTime" type="xs:integer" />
							<xs:element name="direction" type="xs:integer" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== clacoa/epam_edu/Chuggington/src/main/resources/Chuggington.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:trains xmlns:p="Chuggington" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="Chuggington trains.xsd ">
	<p:train>
		<p:name>Wilson</p:name>
		<p:throwTunnelTime>3</p:throwTunnelTime>
		<p:direction>0</p:direction>
	</p:train>
	<p:train>
		<p:name>Koko</p:name>
		<p:throwTunnelTime>5</p:throwTunnelTime>
		<p:direction>0</p:direction>
	</p:train>
	<p:train>
		<p:name>Brewster</p:name>
		<p:throwTunnelTime>8</p:throwTunnelTime>
		<p:direction>1</p:direction>
	</p:train>
	<p:train>
		<p:name>Dunbar</p:name>
		<p:throwTunnelTime>10</p:throwTunnelTime>
		<p:direction>0</p:direction>
	</p:train>
	<p:train>
		<p:name>Olwin</p:name>
		<p:throwTunnelTime>4</p:throwTunnelTime>
		<p:direction>0</p:direction>
	</p:train>
	<p:train>
		<p:name>Mtambo</p:name>
		<p:throwTunnelTime>7</p:throwTunnelTime>
		<p:direction>1</p:direction>
	</p:train>
	<p:train>
		<p:name>Calley</p:name>
		<p:throwTunnelTime>9</p:throwTunnelTime>
		<p:direction>1</p:direction>
	</p:train>
	<p:train>
		<p:name>Irving</p:name>
		<p:throwTunnelTime>10</p:throwTunnelTime>
		<p:direction>0</p:direction>
	</p:train>
	<p:train>
		<p:name>Pete</p:name>
		<p:throwTunnelTime>15</p:throwTunnelTime>
		<p:direction>1</p:direction>
	</p:train>
	<p:train>
		<p:name>Harrison</p:name>
		<p:throwTunnelTime>2</p:throwTunnelTime>
		<p:direction>0</p:direction>
	</p:train>
	<p:train>
		<p:name>Emery</p:name>
		<p:throwTunnelTime>6</p:throwTunnelTime>
		<p:direction>0</p:direction>
	</p:train>
	<p:train>
		<p:name>Hodge</p:name>
		<p:throwTunnelTime>6</p:throwTunnelTime>
		<p:direction>1</p:direction>
	</p:train>
	<p:train>
		<p:name>Frostini</p:name>
		<p:throwTunnelTime>5</p:throwTunnelTime>
		<p:direction>0</p:direction>
	</p:train>
	<p:train>
		<p:name>Hoot</p:name>
		<p:throwTunnelTime>5</p:throwTunnelTime>
		<p:direction>1</p:direction>
	</p:train>
	<p:train>
		<p:name>Toot</p:name>
		<p:throwTunnelTime>5</p:throwTunnelTime>
		<p:direction>0</p:direction>
	</p:train>
	<p:train>
		<p:name>Zephie</p:name>
		<p:throwTunnelTime>7</p:throwTunnelTime>
		<p:direction>0</p:direction>
	</p:train>
	<p:train>
		<p:name>Zack</p:name>
		<p:throwTunnelTime>5</p:throwTunnelTime>
		<p:direction>0</p:direction>
	</p:train>
		<p:train>
		<p:name>Wilson</p:name>
		<p:throwTunnelTime>3</p:throwTunnelTime>
		<p:direction>1</p:direction>
	</p:train>
	<p:train>
		<p:name>Koko</p:name>
		<p:throwTunnelTime>5</p:throwTunnelTime>
		<p:direction>1</p:direction>
	</p:train>
	<p:train>
		<p:name>Brewster</p:name>
		<p:throwTunnelTime>8</p:throwTunnelTime>
		<p:direction>0</p:direction>
	</p:train>
	<p:train>
		<p:name>Dunbar</p:name>
		<p:throwTunnelTime>10</p:throwTunnelTime>
		<p:direction>0</p:direction>
	</p:train>
	<p:train>
		<p:name>Olwin</p:name>
		<p:throwTunnelTime>4</p:throwTunnelTime>
		<p:direction>1</p:direction>
	</p:train>
	<p:train>
		<p:name>Mtambo</p:name>
		<p:throwTunnelTime>7</p:throwTunnelTime>
		<p:direction>0</p:direction>
	</p:train>
	<p:train>
		<p:name>Calley</p:name>
		<p:throwTunnelTime>9</p:throwTunnelTime>
		<p:direction>0</p:direction>
	</p:train>
	<p:train>
		<p:name>Irving</p:name>
		<p:throwTunnelTime>10</p:throwTunnelTime>
		<p:direction>1</p:direction>
	</p:train>
	<p:train>
		<p:name>Pete</p:name>
		<p:throwTunnelTime>15</p:throwTunnelTime>
		<p:direction>0</p:direction>
	</p:train>
	<p:train>
		<p:name>Harrison</p:name>
		<p:throwTunnelTime>2</p:throwTunnelTime>
		<p:direction>1</p:direction>
	</p:train>
	<p:train>
		<p:name>Emery</p:name>
		<p:throwTunnelTime>6</p:throwTunnelTime>
		<p:direction>1</p:direction>
	</p:train>
	<p:train>
		<p:name>Hodge</p:name>
		<p:throwTunnelTime>6</p:throwTunnelTime>
		<p:direction>0</p:direction>
	</p:train>
	<p:train>
		<p:name>Frostini</p:name>
		<p:throwTunnelTime>5</p:throwTunnelTime>
		<p:direction>1</p:direction>
	</p:train>
	<p:train>
		<p:name>Hoot</p:name>
		<p:throwTunnelTime>5</p:throwTunnelTime>
		<p:direction>0</p:direction>
	</p:train>
	<p:train>
		<p:name>Toot</p:name>
		<p:throwTunnelTime>5</p:throwTunnelTime>
		<p:direction>1</p:direction>
	</p:train>
	<p:train>
		<p:name>Zephie</p:name>
		<p:throwTunnelTime>7</p:throwTunnelTime>
		<p:direction>1</p:direction>
	</p:train>
	<p:train>
		<p:name>Zack</p:name>
		<p:throwTunnelTime>5</p:throwTunnelTime>
		<p:direction>1</p:direction>
	</p:train>


</p:trains>
